// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Tape$ReactTemplate = require("./Tape.bs.js");

var component = ReasonReact.statelessComponent("Page");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

var tape = /* record */[
  /* previous : :: */[
    /* One */1,
    /* [] */0
  ],
  /* current : One */1,
  /* next : :: */[
    /* Zero */0,
    /* :: */[
      /* Zero */0,
      /* :: */[
        /* One */1,
        /* [] */0
      ]
    ]
  ]
];

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  onClick: Curry._1(self[/* handle */0], handleClick)
                }, React.createElement("pre", undefined, Tape$ReactTemplate.toString(tape)));
    });
  return newrecord;
}

exports.component = component;
exports.handleClick = handleClick;
exports.tape = tape;
exports.make = make;
/* component Not a pure module */
