// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function verbPhrase(headMove) {
  switch (headMove) {
    case 0 : 
        return "move left";
    case 1 : 
        return "move right";
    case 2 : 
        return "not move";
    
  }
}

exports.verbPhrase = verbPhrase;
/* No side effect */
