// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Symbol$ReactTemplate = require("./Symbol.bs.js");

function getSymbols(tape) {
  return List.concat(/* :: */[
              tape[/* previous */0],
              /* :: */[
                /* :: */[
                  tape[/* current */1],
                  /* [] */0
                ],
                /* :: */[
                  tape[/* next */2],
                  /* [] */0
                ]
              ]
            ]);
}

function toString(tape) {
  var previous = $$String.concat("", List.map(Symbol$ReactTemplate.toString, tape[/* previous */0]));
  var next = $$String.concat("", List.map(Symbol$ReactTemplate.toString, tape[/* next */2]));
  var current = ">" + (Symbol$ReactTemplate.toString(tape[/* current */1]) + "<");
  return previous + (current + next);
}

exports.getSymbols = getSymbols;
exports.toString = toString;
/* No side effect */
